name: build

on:
  workflow_dispatch:

jobs:
  build-nx:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:20260219
    env:
      BASE_URL: https://github.com/dragonflylee/switchfin/releases/download/switch-portlibs
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Update deko3d dependencies
      run: |
        dkp-pacman --noconfirm -R switch-libmpv
        dkp-pacman --noconfirm -U $BASE_URL/libuam-master-1-any.pkg.tar.zst
    - name: Update dependencies
      run: |
        for pkg in mbedtls-3.6.7-1 libssh2-1.11.1-1 dav1d-1.5.4-1 curl-8.16.0-3 ffmpeg-7.1.5-5 libmpv-deko3d-0.36.0-5; do
          dkp-pacman --noconfirm -U $BASE_URL/switch-${pkg}-any.pkg.tar.zst
        done
        git config --system --add safe.directory $GITHUB_WORKSPACE
    - name: Build nro
      run: |
        cmake -B build \
          -DUSE_DEKO3D=ON \
          -DCMAKE_BUILD_TYPE=Release \
          -DPLATFORM_SWITCH=ON \
          -DUSE_LIBUSBHSFS=OFF \
          -DUSE_MUPDF=OFF \
          -DBUILTIN_NSP=OFF \
          -DVERSION_BUILD=${{ github.run_number }}
        make -C build SwitchFnTv.nro -j$(nproc)
    - name: Upload nro
      uses: actions/upload-artifact@v6
      with:
        name: SwitchFnTv-NintendoSwitch-deko3d
        path: build/SwitchFnTv.nro
